# Generated by Django 3.2 on 2021-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('token', models.CharField(max_length=255)),
                ('del_flag', models.DecimalField(decimal_places=0, max_digits=1)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
