# Generated by Django 3.2 on 2021-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='del_flag',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
