# Generated by Django 3.2 on 2021-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0002_auto_20210615_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
