# Generated by Django 3.2 on 2021-06-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0003_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
