# Generated by Django 3.2 on 2021-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0004_remove_users_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['create_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='remark',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
