# Generated by Django 3.2 on 2021-06-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0005_auto_20210616_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
