# Generated by Django 3.2 on 2021-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0006_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remark',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
