# Generated by Django 3.2 on 2021-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0007_auto_20210616_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remark',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
