# Generated by Django 3.2 on 2021-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0008_auto_20210616_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
