# Generated by Django 3.2 on 2021-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0009_auto_20210616_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
