# Generated by Django 3.2 on 2021-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0010_auto_20210616_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=256),
        ),
    ]
