# Generated by Django 3.2 on 2021-06-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
