# Generated by Django 3.2 on 2021-06-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
